# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 17:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import redactor.fields
import uuid
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AboutPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.TextField(blank=True, null=True)),
                ('main_text', models.TextField(blank=True, null=True)),
                ('bottom_text', models.TextField(blank=True, null=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.AboutPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPagePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.AboutPage')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_order', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.TextField(blank=True, null=True)),
                ('main_text', models.TextField(blank=True, null=True)),
                ('bottom_text', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts Page',
            },
        ),
        migrations.CreateModel(
            name='ContactsPagePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ContactsPage')),
            ],
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FAQPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.TextField(blank=True, null=True)),
                ('main_text', models.TextField(blank=True, null=True)),
                ('bottom_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FAQPage')),
            ],
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('faq_page_by_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FAQPageByLanguage')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('photos_order', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='GalleryByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=5)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=100)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.IntegerField(choices=[(0, 'White page style'), (1, 'Black page style')], default=0)),
                ('layout', models.IntegerField(choices=[(0, 'Grid landing'), (1, 'Full screen sliding')], default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
            ],
            options={
                'verbose_name': 'Page Default Settings',
                'verbose_name_plural': 'Page Default Settings',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=website.models.image_path)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='PricePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Price Page',
            },
        ),
        migrations.CreateModel(
            name='PricePageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.TextField(blank=True, null=True)),
                ('main_text', models.TextField(blank=True, null=True)),
                ('bottom_text', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
                ('pricepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.PricePage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricePagePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo', unique=True)),
                ('price_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.PricePage')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reviews-photos/')),
                ('text_editor', redactor.fields.RedactorField(verbose_name='Review')),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='gallerybylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='faqphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo', unique=True),
        ),
        migrations.AddField(
            model_name='faqpagebylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language', unique=True),
        ),
        migrations.AddField(
            model_name='contactspagephoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo', unique=True),
        ),
        migrations.AddField(
            model_name='categorybylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='aboutpagephoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo', unique=True),
        ),
        migrations.AddField(
            model_name='aboutpagebylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='photocategory',
            unique_together=set([('photo', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='gallerybylanguage',
            unique_together=set([('gallery', 'language')]),
        ),
    ]
