# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('reviewpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ReviewPage')),
            ],
        ),
    ]
