# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 14:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('reviewpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ReviewPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagephoto',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.AboutPage'),
        ),
        migrations.AlterField(
            model_name='contactspagephoto',
            name='contacts_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.ContactsPage'),
        ),
        migrations.AlterField(
            model_name='faqphoto',
            name='faq_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.FaqPage'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Photo'),
        ),
        migrations.AlterField(
            model_name='pricepagephoto',
            name='price_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.PricePage'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Review'),
        ),
        migrations.AddField(
            model_name='reviewpage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
    ]
