# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 15:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryByLanguage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('categorybylanguage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CategoryByLanguage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaqPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryByLanguage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('gallerybylanguage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.GalleryByLanguage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('indexpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.IndexPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricePage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetouchPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name_in_menu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RetouchPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('retouchpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.RetouchPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPage_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('reviewpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ReviewPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_site_verification', models.CharField(max_length=1000)),
                ('google_analytics_verification', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='page_name_in_menu',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='page_name_in_menu',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactspage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='page_name_in_menu',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqpage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='page_name_in_menu',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricepage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagephoto',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.AboutPage'),
        ),
        migrations.AlterField(
            model_name='contactspagephoto',
            name='contacts_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.ContactsPage'),
        ),
        migrations.AlterField(
            model_name='faqphoto',
            name='faq_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.FaqPage'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Photo'),
        ),
        migrations.AlterField(
            model_name='pricepagephoto',
            name='price_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.PricePage'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Review'),
        ),
        migrations.AddField(
            model_name='reviewpage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='retouchpage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='pricepage_seo',
            name='pricepage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.PricePage'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='faqpage_seo',
            name='faqpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.FaqPage'),
        ),
        migrations.AddField(
            model_name='contactspage_seo',
            name='contactspage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ContactsPage'),
        ),
        migrations.AddField(
            model_name='aboutpage_seo',
            name='aboutpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.AboutPage'),
        ),
    ]
