# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocategory',
            options={'verbose_name': 'Photo for category', 'verbose_name_plural': 'Photos for category'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='text_editor',
            new_name='review',
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 3, 18, 16, 14, 803888, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 3, 18, 16, 23, 2106, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language', unique=True),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Gallery'),
        ),
        migrations.AlterField(
            model_name='pricepage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AlterField(
            model_name='pricepage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo'),
        ),
    ]
