# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.ImageField(upload_to=website.models.image_path)),
                ('after', models.ImageField(upload_to=website.models.image_path)),
            ],
        ),
    ]
