# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.ImageField(upload_to='retouch/')),
                ('after', models.ImageField(upload_to='retouch/')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pagesettings',
            options={'verbose_name': 'Default Settings', 'verbose_name_plural': 'Default Settings'},
        ),
        migrations.AlterModelOptions(
            name='photocategory',
            options={'verbose_name': 'Photo for category', 'verbose_name_plural': 'Photos for category'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='text_editor',
            new_name='review',
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 3, 18, 22, 59, 536364, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 3, 18, 23, 17, 206713, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language', unique=True),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Gallery'),
        ),
        migrations.AlterField(
            model_name='pricepage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AlterField(
            model_name='pricepage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo'),
        ),
    ]
