# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160801_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesettings',
            options={'verbose_name': 'Default Settings', 'verbose_name_plural': 'Default Settings'},
        ),
    ]
