# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160803_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_side_photo', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.AddField(
            model_name='aboutpagephoto',
            name='is_side_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactspagephoto',
            name='is_side_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faqphoto',
            name='is_side_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricepagephoto',
            name='is_side_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Review'),
        ),
    ]
