# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-07 10:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_reviewpage_reviewpage_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagephoto',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.AboutPage'),
        ),
        migrations.AlterField(
            model_name='contactspagephoto',
            name='contacts_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.ContactsPage'),
        ),
        migrations.AlterField(
            model_name='faqphoto',
            name='faq_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.FaqPage'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Photo'),
        ),
        migrations.AlterField(
            model_name='pricepagephoto',
            name='price_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.PricePage'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Review'),
        ),
    ]
