# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_comparisonphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonphoto',
            name='after',
            field=models.ImageField(upload_to='retouch/'),
        ),
        migrations.AlterField(
            model_name='comparisonphoto',
            name='before',
            field=models.ImageField(upload_to='retouch/'),
        ),
    ]
