# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160801_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonphoto',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
