# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160808_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GallerySeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=156)),
                ('title_for_facebook', models.CharField(max_length=27)),
                ('description_for_facebook', models.CharField(max_length=300)),
                ('image_for_facebook', models.ImageField(upload_to='seo/')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Gallery')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexPagePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='AboutPage_Seo',
            new_name='AboutPageSeo',
        ),
        migrations.RenameModel(
            old_name='ContactsPage_Seo',
            new_name='ContactsPageSeo',
        ),
        migrations.RenameModel(
            old_name='FaqPage_Seo',
            new_name='FaqPageSeo',
        ),
        migrations.RenameModel(
            old_name='IndexPage_Seo',
            new_name='IndexPageSeo',
        ),
        migrations.RenameModel(
            old_name='PricePage_Seo',
            new_name='PricePageSeo',
        ),
        migrations.RenameModel(
            old_name='RetouchPage_Seo',
            new_name='RetouchPageSeo',
        ),
        migrations.RenameModel(
            old_name='ReviewPage_Seo',
            new_name='ReviewPageSeo',
        ),
        migrations.RemoveField(
            model_name='categorybylanguage_seo',
            name='categorybylanguage',
        ),
        migrations.RemoveField(
            model_name='gallerybylanguage_seo',
            name='gallerybylanguage',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='photos_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryByLanguage_Seo',
        ),
        migrations.DeleteModel(
            name='GalleryByLanguage_Seo',
        ),
        migrations.AddField(
            model_name='indexpagephoto',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.IndexPage'),
        ),
        migrations.AddField(
            model_name='indexpagephoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Photo'),
        ),
    ]
