# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160803_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_for_index_grid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_for_index_slider',
            field=models.BooleanField(default=False),
        ),
    ]
