# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160808_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name_in_menu', models.CharField(max_length=100)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('quote', redactor.fields.RedactorField(blank=True, null=True, verbose_name='Quote')),
                ('quote_author', redactor.fields.RedactorField(blank=True, null=True, verbose_name='Quote author')),
                ('text', redactor.fields.RedactorField(blank=True, null=True, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100)),
                ('heading', redactor.fields.RedactorField(verbose_name='Heading')),
                ('heading_text', redactor.fields.RedactorField(verbose_name='Heading Text')),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('phone_number_display', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number_call', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_form_heading', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_form_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_form_email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_form_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_form_question', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_form_message', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_form_send_button_text', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('page_name_in_menu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PricePageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('page_name_in_menu', models.CharField(max_length=100)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
            ],
        ),
        migrations.CreateModel(
            name='RetouchPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name_in_menu', models.CharField(max_length=100)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPageByLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name_in_menu', models.CharField(max_length=100)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_name_in_menu',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='quote_author',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='text',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='contact_form_email',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='contact_form_heading',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='contact_form_message',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='contact_form_name',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='contact_form_phone_number',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='contact_form_question',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='contact_form_send_button_text',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='heading_text',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='phone_number_call',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='phone_number_display',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='page_name_in_menu',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='pricepage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='pricepage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='pricepage',
            name='page_name_in_menu',
        ),
        migrations.RemoveField(
            model_name='retouchpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='retouchpage',
            name='page_name_in_menu',
        ),
        migrations.RemoveField(
            model_name='reviewpage',
            name='language',
        ),
        migrations.AddField(
            model_name='aboutpageseo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='contactspageseo',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='faqpageseo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='indexpageseo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='pricepageseo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='question_faqpage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='retouchpage',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 9, 12, 22, 9, 423900, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retouchpageseo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='reviewpage',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 9, 12, 22, 26, 868221, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewpageseo',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='retouchpagebylanguage',
            name='retouchpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.RetouchPage'),
        ),
        migrations.AddField(
            model_name='pricepagebylanguage',
            name='pricepage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.PricePage'),
        ),
        migrations.AddField(
            model_name='indexpagebylanguage',
            name='indexpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.IndexPage'),
        ),
        migrations.AddField(
            model_name='indexpagebylanguage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='faqpagebylanguage',
            name='faqpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FaqPage'),
        ),
        migrations.AddField(
            model_name='faqpagebylanguage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='contactspagebylanguage',
            name='contactspage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ContactsPage'),
        ),
        migrations.AddField(
            model_name='contactspagebylanguage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
        migrations.AddField(
            model_name='aboutpagebylanguage',
            name='aboutpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.AboutPage'),
        ),
        migrations.AddField(
            model_name='aboutpagebylanguage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Language'),
        ),
    ]
