# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_comparisonphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_for_about_us_page_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_for_contacts_page_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_for_faq_page_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_for_price_page_side',
            field=models.BooleanField(default=False),
        ),
    ]
