# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160809_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ReviewPage'),
        ),
        migrations.AddField(
            model_name='reviewpagebylanguage',
            name='reviewpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ReviewPage'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.ReviewPage'),
        ),
    ]
