# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160801_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_for_review_page_side',
            field=models.BooleanField(default=False),
        ),
    ]
