# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160810_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name_plural': 'Index Page'},
        ),
    ]
