# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160810_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Review'),
        ),
    ]
