# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160819_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='layout',
            field=models.IntegerField(choices=[(1, 'Slider layout'), (2, 'Grid layout 2x*'), (3, 'Grid layout 3x*'), (4, 'Grid layout 4x*'), (5, 'Grid layout 5x*'), (6, 'Grid layout 6x*')], default=4),
        ),
    ]
