# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160810_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewpage',
            new_name='review_page',
        ),
        migrations.RenameField(
            model_name='reviewpagebylanguage',
            old_name='reviewpage',
            new_name='review_page',
        ),
    ]
