# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160825_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('my_order',), 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
