# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160825_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Galleries'},
        ),
    ]
