# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160810_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_page',
        ),
        migrations.AddField(
            model_name='reviewbylanguage',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewbylanguage',
            name='review_text',
            field=redactor.fields.RedactorField(default='', verbose_name='Review'),
            preserve_default=False,
        ),
    ]
