# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAutoReplySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text', redactor.fields.RedactorField(verbose_name='Auto Reply text')),
            ],
        ),
    ]
